"use client";

export type ModuleCategory =
  | "controller"
  | "sensor"
  | "power"
  | "communication"
  | "actuator"
  | "ui"
  | "structure"
  | "visual";

export type ModuleShape =
  | "board"
  | "chip"
  | "box"
  | "panel"
  | "connector"
  | "wire"
  | "shell";

export type ModuleSize = "s" | "m" | "l";

export type ModuleMountType =
  | "base"
  | "stack"
  | "side"
  | "external"
  | "floating";

export type PreferredPlacement =
  | "center"
  | "top"
  | "bottom"
  | "left"
  | "right"
  | "front"
  | "rear"
  | "outer";

export type AccentType = "data" | "power" | "signal" | "neutral";

export type SceneRole = "core" | "support" | "io" | "display" | "shell";

export type ModuleComponent = {
  id: string;
  name: string;
  category: ModuleCategory;
  shape: ModuleShape;
  size: ModuleSize;
  mountType: ModuleMountType;
  anchorPoints: string[];
  connectableTo: string[];
  preferredPlacement: PreferredPlacement;
  visualStyle: {
    emissive?: boolean;
    label?: boolean;
    accentType?: AccentType;
  };
  sceneRole: SceneRole;
  keywords: string[];
};

const MODULE_COMPONENTS: ModuleComponent[] = [
  {
    id: "esp32_board",
    name: "ESP32 开发板",
    category: "controller",
    shape: "board",
    size: "m",
    mountType: "base",
    anchorPoints: ["power_in", "data_bus", "ui_bus", "comm_bus"],
    connectableTo: ["sensor", "power", "communication", "ui", "actuator"],
    preferredPlacement: "center",
    visualStyle: { emissive: true, label: true, accentType: "signal" },
    sceneRole: "core",
    keywords: ["esp32", "wifi", "mcu", "主控", "控制板"],
  },
  {
    id: "stm32_board",
    name: "STM32 控制板",
    category: "controller",
    shape: "board",
    size: "m",
    mountType: "base",
    anchorPoints: ["power_in", "data_bus", "motor_bus", "comm_bus"],
    connectableTo: ["sensor", "power", "communication", "ui", "actuator"],
    preferredPlacement: "center",
    visualStyle: { emissive: true, label: true, accentType: "signal" },
    sceneRole: "core",
    keywords: ["stm32", "控制器", "主控", "工业控制"],
  },
  {
    id: "io_expander",
    name: "IO 扩展模块",
    category: "controller",
    shape: "board",
    size: "s",
    mountType: "stack",
    anchorPoints: ["io_in", "io_out"],
    connectableTo: ["controller", "actuator", "ui"],
    preferredPlacement: "right",
    visualStyle: { label: true, accentType: "neutral" },
    sceneRole: "support",
    keywords: ["io", "扩展", "接口扩展"],
  },
  {
    id: "wifi_module",
    name: "WiFi 模块",
    category: "communication",
    shape: "chip",
    size: "s",
    mountType: "side",
    anchorPoints: ["comm_in", "antenna"],
    connectableTo: ["controller", "ui"],
    preferredPlacement: "top",
    visualStyle: { emissive: true, label: true, accentType: "signal" },
    sceneRole: "io",
    keywords: ["wifi", "无线", "联网", "上传"],
  },
  {
    id: "bluetooth_module",
    name: "蓝牙模块",
    category: "communication",
    shape: "chip",
    size: "s",
    mountType: "side",
    anchorPoints: ["comm_in", "antenna"],
    connectableTo: ["controller", "ui"],
    preferredPlacement: "top",
    visualStyle: { emissive: true, label: true, accentType: "signal" },
    sceneRole: "io",
    keywords: ["蓝牙", "ble", "近距离通信"],
  },
  {
    id: "ethernet_module",
    name: "以太网模块",
    category: "communication",
    shape: "box",
    size: "s",
    mountType: "side",
    anchorPoints: ["eth", "comm_in"],
    connectableTo: ["controller"],
    preferredPlacement: "rear",
    visualStyle: { label: true, accentType: "signal" },
    sceneRole: "io",
    keywords: ["以太网", "网口", "lan"],
  },
  {
    id: "rs485_module",
    name: "RS485 模块",
    category: "communication",
    shape: "connector",
    size: "s",
    mountType: "side",
    anchorPoints: ["rs485"],
    connectableTo: ["controller", "actuator"],
    preferredPlacement: "rear",
    visualStyle: { label: true, accentType: "signal" },
    sceneRole: "io",
    keywords: ["rs485", "总线", "工业通信"],
  },
  {
    id: "can_module",
    name: "CAN 模块",
    category: "communication",
    shape: "connector",
    size: "s",
    mountType: "side",
    anchorPoints: ["can"],
    connectableTo: ["controller", "actuator"],
    preferredPlacement: "rear",
    visualStyle: { label: true, accentType: "signal" },
    sceneRole: "io",
    keywords: ["can", "总线", "车载"],
  },
  {
    id: "lte_module",
    name: "4G 模块",
    category: "communication",
    shape: "box",
    size: "m",
    mountType: "external",
    anchorPoints: ["sim", "antenna", "comm_in"],
    connectableTo: ["controller"],
    preferredPlacement: "top",
    visualStyle: { emissive: true, label: true, accentType: "signal" },
    sceneRole: "io",
    keywords: ["4g", "lte", "蜂窝网络", "远程"],
  },
  {
    id: "temp_humidity_sensor",
    name: "温湿度传感器",
    category: "sensor",
    shape: "chip",
    size: "s",
    mountType: "external",
    anchorPoints: ["sensor_out"],
    connectableTo: ["controller"],
    preferredPlacement: "outer",
    visualStyle: { emissive: true, label: true, accentType: "data" },
    sceneRole: "io",
    keywords: ["温湿度", "环境监测", "采集"],
  },
  {
    id: "imu_sensor",
    name: "IMU 传感器",
    category: "sensor",
    shape: "chip",
    size: "s",
    mountType: "floating",
    anchorPoints: ["sensor_out"],
    connectableTo: ["controller"],
    preferredPlacement: "outer",
    visualStyle: { emissive: true, label: true, accentType: "data" },
    sceneRole: "io",
    keywords: ["imu", "姿态", "加速度", "陀螺仪"],
  },
  {
    id: "camera_sensor",
    name: "摄像头模组",
    category: "sensor",
    shape: "panel",
    size: "m",
    mountType: "external",
    anchorPoints: ["video_out"],
    connectableTo: ["controller", "ui"],
    preferredPlacement: "front",
    visualStyle: { label: true, accentType: "data" },
    sceneRole: "io",
    keywords: ["摄像头", "图像", "视觉"],
  },
  {
    id: "distance_sensor",
    name: "距离传感器",
    category: "sensor",
    shape: "connector",
    size: "s",
    mountType: "external",
    anchorPoints: ["sensor_out"],
    connectableTo: ["controller"],
    preferredPlacement: "front",
    visualStyle: { label: true, accentType: "data" },
    sceneRole: "io",
    keywords: ["距离", "测距", "tof", "超声"],
  },
  {
    id: "current_sensor",
    name: "电流采样模块",
    category: "sensor",
    shape: "board",
    size: "s",
    mountType: "stack",
    anchorPoints: ["power_in", "sensor_out"],
    connectableTo: ["controller", "power"],
    preferredPlacement: "bottom",
    visualStyle: { label: true, accentType: "power" },
    sceneRole: "support",
    keywords: ["电流", "功耗", "采样"],
  },
  {
    id: "relay_module",
    name: "继电器模块",
    category: "actuator",
    shape: "box",
    size: "m",
    mountType: "side",
    anchorPoints: ["control_in", "power_in", "load_out"],
    connectableTo: ["controller", "power"],
    preferredPlacement: "right",
    visualStyle: { label: true, accentType: "signal" },
    sceneRole: "io",
    keywords: ["继电器", "开关控制", "输出"],
  },
  {
    id: "motor_driver",
    name: "电机驱动模块",
    category: "actuator",
    shape: "board",
    size: "m",
    mountType: "side",
    anchorPoints: ["control_in", "power_in", "motor_out"],
    connectableTo: ["controller", "power"],
    preferredPlacement: "right",
    visualStyle: { label: true, accentType: "power" },
    sceneRole: "io",
    keywords: ["电机", "驱动", "马达"],
  },
  {
    id: "led_driver",
    name: "LED 驱动模块",
    category: "actuator",
    shape: "board",
    size: "s",
    mountType: "side",
    anchorPoints: ["control_in", "power_in", "light_out"],
    connectableTo: ["controller", "power", "ui"],
    preferredPlacement: "right",
    visualStyle: { emissive: true, label: true, accentType: "power" },
    sceneRole: "io",
    keywords: ["led", "灯光", "驱动"],
  },
  {
    id: "servo_driver",
    name: "舵机驱动模块",
    category: "actuator",
    shape: "board",
    size: "s",
    mountType: "side",
    anchorPoints: ["control_in", "power_in", "servo_out"],
    connectableTo: ["controller", "power"],
    preferredPlacement: "right",
    visualStyle: { label: true, accentType: "signal" },
    sceneRole: "io",
    keywords: ["舵机", "执行", "驱动"],
  },
  {
    id: "battery_pack",
    name: "电池包",
    category: "power",
    shape: "box",
    size: "m",
    mountType: "base",
    anchorPoints: ["power_out"],
    connectableTo: ["controller", "sensor", "communication", "actuator", "ui"],
    preferredPlacement: "bottom",
    visualStyle: { emissive: true, label: true, accentType: "power" },
    sceneRole: "support",
    keywords: ["电池", "供电", "便携", "续航"],
  },
  {
    id: "dc_input",
    name: "DC 输入",
    category: "power",
    shape: "connector",
    size: "s",
    mountType: "external",
    anchorPoints: ["power_out"],
    connectableTo: ["power", "controller"],
    preferredPlacement: "rear",
    visualStyle: { label: true, accentType: "power" },
    sceneRole: "support",
    keywords: ["dc", "电源输入", "适配器"],
  },
  {
    id: "buck_converter",
    name: "Buck 降压模块",
    category: "power",
    shape: "board",
    size: "s",
    mountType: "stack",
    anchorPoints: ["power_in", "power_out"],
    connectableTo: ["power", "controller", "sensor", "communication"],
    preferredPlacement: "bottom",
    visualStyle: { label: true, accentType: "power" },
    sceneRole: "support",
    keywords: ["buck", "降压", "电源管理"],
  },
  {
    id: "power_protection",
    name: "电源保护模块",
    category: "power",
    shape: "board",
    size: "s",
    mountType: "stack",
    anchorPoints: ["power_in", "power_out"],
    connectableTo: ["power", "controller"],
    preferredPlacement: "bottom",
    visualStyle: { label: true, accentType: "power" },
    sceneRole: "support",
    keywords: ["保护", "防反接", "保险"],
  },
  {
    id: "display_panel",
    name: "显示屏",
    category: "ui",
    shape: "panel",
    size: "l",
    mountType: "external",
    anchorPoints: ["ui_in"],
    connectableTo: ["controller"],
    preferredPlacement: "front",
    visualStyle: { emissive: true, label: true, accentType: "data" },
    sceneRole: "display",
    keywords: ["显示", "屏幕", "本地显示", "界面"],
  },
  {
    id: "button_pad",
    name: "按钮组",
    category: "ui",
    shape: "panel",
    size: "s",
    mountType: "external",
    anchorPoints: ["input_out"],
    connectableTo: ["controller"],
    preferredPlacement: "front",
    visualStyle: { label: true, accentType: "neutral" },
    sceneRole: "display",
    keywords: ["按钮", "输入", "按键"],
  },
  {
    id: "knob_input",
    name: "旋钮输入",
    category: "ui",
    shape: "connector",
    size: "s",
    mountType: "external",
    anchorPoints: ["input_out"],
    connectableTo: ["controller"],
    preferredPlacement: "front",
    visualStyle: { label: true, accentType: "neutral" },
    sceneRole: "display",
    keywords: ["旋钮", "调节", "编码器"],
  },
  {
    id: "status_led",
    name: "状态指示灯",
    category: "ui",
    shape: "connector",
    size: "s",
    mountType: "external",
    anchorPoints: ["signal_in"],
    connectableTo: ["controller", "power"],
    preferredPlacement: "front",
    visualStyle: { emissive: true, label: true, accentType: "signal" },
    sceneRole: "display",
    keywords: ["led", "指示灯", "状态灯"],
  },
  {
    id: "base_plate",
    name: "底板",
    category: "structure",
    shape: "board",
    size: "l",
    mountType: "base",
    anchorPoints: ["mount"],
    connectableTo: ["structure", "controller", "power"],
    preferredPlacement: "bottom",
    visualStyle: { label: false, accentType: "neutral" },
    sceneRole: "shell",
    keywords: ["底板", "基座", "结构"],
  },
  {
    id: "shell_body",
    name: "外壳",
    category: "structure",
    shape: "shell",
    size: "l",
    mountType: "external",
    anchorPoints: ["mount"],
    connectableTo: ["structure"],
    preferredPlacement: "outer",
    visualStyle: { label: false, accentType: "neutral" },
    sceneRole: "shell",
    keywords: ["外壳", "盒体", "机身"],
  },
  {
    id: "top_cover",
    name: "顶盖",
    category: "structure",
    shape: "panel",
    size: "l",
    mountType: "external",
    anchorPoints: ["mount"],
    connectableTo: ["structure"],
    preferredPlacement: "top",
    visualStyle: { label: false, accentType: "neutral" },
    sceneRole: "shell",
    keywords: ["顶盖", "上盖", "外壳"],
  },
  {
    id: "mount_bracket",
    name: "安装支架",
    category: "structure",
    shape: "connector",
    size: "m",
    mountType: "base",
    anchorPoints: ["mount"],
    connectableTo: ["structure", "controller", "sensor"],
    preferredPlacement: "outer",
    visualStyle: { label: false, accentType: "neutral" },
    sceneRole: "shell",
    keywords: ["支架", "安装", "固定"],
  },
  {
    id: "label_tag",
    name: "标签牌",
    category: "visual",
    shape: "panel",
    size: "s",
    mountType: "floating",
    anchorPoints: ["visual"],
    connectableTo: ["visual"],
    preferredPlacement: "outer",
    visualStyle: { emissive: false, label: true, accentType: "neutral" },
    sceneRole: "support",
    keywords: ["标签", "说明", "文字"],
  },
  {
    id: "data_flow_line",
    name: "数据流线",
    category: "visual",
    shape: "wire",
    size: "m",
    mountType: "floating",
    anchorPoints: ["from", "to"],
    connectableTo: ["visual"],
    preferredPlacement: "outer",
    visualStyle: { emissive: true, label: false, accentType: "data" },
    sceneRole: "support",
    keywords: ["连线", "数据流", "路径"],
  },
  {
    id: "signal_particle",
    name: "信号粒子",
    category: "visual",
    shape: "connector",
    size: "s",
    mountType: "floating",
    anchorPoints: ["path"],
    connectableTo: ["visual"],
    preferredPlacement: "outer",
    visualStyle: { emissive: true, label: false, accentType: "signal" },
    sceneRole: "support",
    keywords: ["粒子", "动画", "信号"],
  },
  {
    id: "highlight_frame",
    name: "高亮框",
    category: "visual",
    shape: "panel",
    size: "m",
    mountType: "floating",
    anchorPoints: ["focus"],
    connectableTo: ["visual"],
    preferredPlacement: "outer",
    visualStyle: { emissive: true, label: false, accentType: "signal" },
    sceneRole: "support",
    keywords: ["高亮", "聚焦", "强调"],
  },
];

export const MODULE_REGISTRY: Record<string, ModuleComponent> =
  MODULE_COMPONENTS.reduce<Record<string, ModuleComponent>>((acc, module) => {
    acc[module.id] = module;
    return acc;
  }, {});

export const MODULE_IDS = MODULE_COMPONENTS.map((module) => module.id);
